source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '9.0'

target 'InterstitialExample' do
  use_frameworks!

  # Pods for InterstitialExample
  pod 'YandexMobileAds/Dynamic'

end
