source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '8.0'

target 'AdMobNativeAdapterExample' do
  use_frameworks!
  pod 'YandexMobileAdsAdMobAdapters/Dynamic'
  pod 'YandexMobileAds/Dynamic'
end

