source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '9.0'

target 'AdFoxMediationInterstitialExample' do
  use_frameworks!
  pod 'AdMobYandexMobileAdsAdapters/Dynamic'
  pod 'AppLovinYandexMobileAdsAdapters/Dynamic'
  pod 'FacebookYandexMobileAdsAdapters/Dynamic'
  pod 'IronSourceYandexMobileAdsAdapters/Dynamic'
  pod 'MoPubYandexMobileAdsAdapters/Dynamic'
  pod 'MyTargetYandexMobileAdsAdapters/Dynamic'
  pod 'StartAppYandexMobileAdsAdapters/Dynamic'
  pod 'UnityAdsYandexMobileAdsAdapters/Dynamic'
  pod 'YandexMobileAds/Dynamic'
end
