source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'YandexMobileAdsExample' do
  pod 'AppLovinYandexMobileAdsAdapters'
  pod 'AdMobYandexMobileAdsAdapters'
  pod 'FacebookYandexMobileAdsAdapters'
  pod 'IronSourceYandexMobileAdsAdapters'
  pod 'MoPubYandexMobileAdsAdapters'
  pod 'MyTargetYandexMobileAdsAdapters'
  pod 'StartAppYandexMobileAdsAdapters'
  pod 'YandexMobileAdsMoPubAdapters'
  pod 'YandexMobileAdsAdMobAdapters'
  pod 'YandexMobileAds'
  pod 'YandexMobileAdsInstream'
end

