source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MoPubInterstitialAdapterExample' do
  use_frameworks!
  pod 'mopub-ios-sdk', '5.16.2'
  pod 'YandexMobileAdsMoPubAdapters/Dynamic'
  pod 'YandexMobileAds/Dynamic'
end
