source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '7.0'

target 'AdMobAdaptersExample' do
  pod 'YandexMobileMetrica' 
  pod 'Google-Mobile-Ads-SDK', '~> 7.0'
  pod 'YandexMobileAds'
end
