source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '9.0'

target 'NativeTemplatesExample' do
  use_frameworks!

  # Pods for NativeTemplatesExample
  pod 'YandexMobileAds/Dynamic'

end
