source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MobileMediationNativeExample' do
  pod 'AdMobYandexMobileAdsAdapters'
  pod 'FacebookYandexMobileAdsAdapters'
  pod 'MoPubYandexMobileAdsAdapters'
  pod 'MyTargetYandexMobileAdsAdapters'
  pod 'YandexMobileAds'
end
