source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MoPubRewardedAdapterExample' do
  use_frameworks!
  pod 'YandexMobileAdsMoPubAdapters/Dynamic'
  pod 'YandexMobileAds/Dynamic'
end
