source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MoPubNativeAdaptersExample' do
  pod 'mopub-ios-sdk', '5.16.2'
  pod 'YandexMobileAdsMoPubAdapters'
  pod 'YandexMobileAds'
end
