source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '9.0'

target 'AdMobInterstitialAdapterExample' do
  pod 'YandexMobileAdsAdMobAdapters'
  pod 'YandexMobileAds'
end
