source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MobileMediationNativeExample' do
  use_frameworks!
  pod 'AdMobYandexMobileAdsAdapters/Dynamic'
  pod 'FacebookYandexMobileAdsAdapters/Dynamic'
  pod 'MoPubYandexMobileAdsAdapters/Dynamic'
  pod 'MyTargetYandexMobileAdsAdapters/Dynamic'
  pod 'YandexMobileAds/Dynamic'
end
