source 'https://cdn.cocoapods.org/'
platform :ios, :deployment_target => '13.0'

target 'ThirdPartyMediationAdapterTemplate' do
  # Pods that are necessary for successful integration with Yandex
  pod 'YandexMobileAds'
end
