source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '8.0'

target 'BannerExample' do
  use_frameworks!

  # Pods for BannerExample
  pod 'YandexMobileAds/Dynamic'

end
