source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '6.0'

target 'MoPubAdaptersExample' do
  pod 'YandexMobileMetrica' 
  pod 'mopub-ios-sdk', '~> 3.12.0'
  pod 'YandexMobileAds'
end
