source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '9.0'

target 'AdFoxMediationRewardedExample' do
  pod 'AdMobYandexMobileAdsAdapters'
  pod 'AppLovinYandexMobileAdsAdapters'
  pod 'FacebookYandexMobileAdsAdapters'
  pod 'MoPubYandexMobileAdsAdapters'
  pod 'StartAppYandexMobileAdsAdapters'
  pod 'UnityAdsYandexMobileAdsAdapters'
  pod 'YandexMobileAds'
end
