source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '10.0'

target 'MobileMediationRewardedExample' do
  pod 'AdMobYandexMobileAdsAdapters'
  pod 'AppLovinYandexMobileAdsAdapters'
  pod 'FacebookYandexMobileAdsAdapters'
  pod 'IronSourceYandexMobileAdsAdapters'
  pod 'MoPubYandexMobileAdsAdapters'
  pod 'MyTargetYandexMobileAdsAdapters'
  pod 'StartAppYandexMobileAdsAdapters'
  pod 'UnityAdsYandexMobileAdsAdapters'
  pod 'YandexMobileAds'
end
