source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '8.0'

target 'AdFoxMediationBannerExample' do
  pod 'AdMobYandexMobileAdsAdapters'
  pod 'FacebookYandexMobileAdsAdapters'
  pod 'MoPubYandexMobileAdsAdapters'
  pod 'MyTargetYandexMobileAdsAdapters'
  pod 'StartAppYandexMobileAdsAdapters'
  pod 'YandexMobileAds'
end
